packages/commerce-events-collectors/package.json, packages/commerce-events-sdk/package.json
=> chore: :memo: use correct homepage path

.github/workflows/publish-latest.yml, .github/workflows/storefront-merge-to-main.yml, package.json, yarn.lock
Adding ci workflow to build storefront packages when codebase is tagged with `v*` and pushed to the main branch
https://jira.corp.adobe.com/browse/DINT-552
Moves all of our repo's into one repository for easier code sharing and developer experience.
-   [ ] I have added …
=> chore: adding prod ci workflow

.github/workflows/merge-to-main.yml, .github/workflows/storefront-merge-to-main.yml, package.json, turbo.json
fixing qa build for storefront packages
=> chore: fix qa build

.github/PACKAGE_WORKFLOW.md, .github/workflows/merge-to-main.yml
adding docs and workflow updating
=> Seg 4 pipeline

.github/workflows/publish-latest.yml, package.json, packages/storefront-events-collector/package.json, packages/storefront-events-sdk/package.json, turbo.json
release v1.1.16
-   [x] My change requires a change to the documentation.
-   [x] I have updated the documentation accordingly.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
=> chore:release v1.1.16

packages/commerce-events-collector-segments/webpack.common.js, packages/storefront-events-collector/src/handlers/product/viewAEP.ts, packages/storefront-events-collector/src/types/aep/productListItem.ts, packages/storefront-events-collector/src/utils/aep/productListItems.ts
Add main image URL to productListItems.
Epic https://jira.corp.adobe.com/browse/DINT-586
Next events should have productImageUrl data in productListItems:
- product View
- add to cart
- cart view
- checkoutstart
- checkoutComplete
- searchResponseReceived 
-   [ ] I have …
=> DINT-590: Add image URL in all events with a product object

packages/commerce-events-collectors/rollup.config.js, packages/commerce-events-sdk/rollup.config.js
Update the default ports in `rollup.config.js` files so they do not conflict with any other packages within the monorepo.
A user should be able to clone this repo, install dependencies, and run `yarn start` (or equivalent command) and have the monorepo and packages launch successfully, without having to modify any tracked files. This change ensures that simple out-of-the-box experience.
`yarn start --filter="@adobe/*"` <-- The filter is necessary so only the exported packages are run, and not the examples
-   [x] I have signed the [Adobe Open Source …
=> Modify Default Ports

packages/commerce-events-collectors/rollup.config.js, packages/commerce-events-collectors/src/contexts/changedProducts.ts, packages/commerce-events-collectors/src/handlers/product/addToCartAEP.ts, packages/commerce-events-collectors/src/handlers/product/removeFromCartAEP.ts, packages/commerce-events-collectors/src/types/aep/commerce.ts, packages/commerce-events-collectors/src/utils/aep/productListItems.ts, packages/commerce-events-collectors/tests/handlers/account/createAccountAEP.test.ts, packages/commerce-events-collectors/tests/handlers/account/editAccountAEP.test.ts, packages/commerce-events-collectors/tests/handlers/account/signInAEP.test.ts, packages/commerce-events-collectors/tests/handlers/account/signOutAEP.test.ts, packages/commerce-events-collectors/tests/handlers/page/viewAEP.test.ts, packages/commerce-events-collectors/tests/handlers/product/addToCartAEP.test.ts, packages/commerce-events-collectors/tests/handlers/product/removeFromCartAEP.test.ts
Some additional unit tests for AEP handlers. Mostly low hanging fruit.
Improve test coverage.
Changes are test code; the changes ARE the tests.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
=> DINT-539: Unit Tests for AEP Handlers

examples/old-collector-example/index.js, examples/old-collector-example/package.json, examples/old-collector-example/slim.html, packages/commerce-events-collectors/lib.d.ts, packages/commerce-events-collectors/package.json, packages/commerce-events-collectors/rollup.config.js, packages/commerce-events-collectors/src/alloy.ts, packages/commerce-events-collectors/src/index.ts, packages/commerce-events-collectors/src/slim.ts, packages/commerce-events-collectors/src/snowplow.ts, packages/commerce-events-collectors/src/types/index.d.ts, packages/storefront-events-collector/src/alloy.ts, packages/storefront-events-collector/src/index.ts, packages/storefront-events-collector/src/types/index.d.ts, yarn.lock
This should fix the alloy issues caused by including the `@adobe/alloy` library. It introduces a new `slim.ts` file that commerce-events-collectors will target to build the slim version, that way the whole alloy library isn't bundled with the build. 
Alloy wasn't working with custom names when provided through external means.
Ran existing tests and they all passes
-   [x] My change requires a change to the documentation.
-   [ ] I …
=> 🐛 DINT-678 custom names for alloy fixes

packages/commerce-events-collectors/src/handlers/search/searchResponseReceivedAEP.ts, packages/storefront-events-collector/src/handlers/search/searchResponseReceivedAEP.ts
Add productImageUrl to products in prodcutListItems for searchResponseAEP handler.
https://jira.corp.adobe.com/browse/DINT-695
https://jira.corp.adobe.com/browse/DINT-695
Tested manually on local machine.
-   [x] All new and …
=> add productImageUrl for searchResponse results

examples/old-collector-example/index.js, packages/commerce-events-collectors/src/contexts/aep.ts, packages/commerce-events-collectors/src/index.ts, packages/commerce-events-collectors/src/slim.ts, packages/commerce-events-collectors/src/types/contexts.d.ts, packages/commerce-events-sdk/src/types/schemas/aep.ts, packages/storefront-events-collector/src/aep/types/alloy.types.ts, packages/storefront-events-collector/src/alloy.ts, packages/storefront-events-collector/src/contexts/aep.ts, packages/storefront-events-collector/src/index.ts, packages/storefront-events-collector/src/types/contexts.d.ts, packages/storefront-events-sdk/src/ContextManager.ts, packages/storefront-events-sdk/src/types/schemas/aep.ts
Allows custom web sdk usage in luma stores.
Clients already using a launch script will inject an alloy instance with that script. These changes allow the client to use the existing alloy instance on the page, with the correct configuration in the experience platform connector.
Tested with magento cloud instances and injecting launch scripts into the page
-   [x] My change requires a change to the documentation.
-   [ ] I have …
=> Dint 689 custom collector in luma

packages/storefront-events-collector/package.json, packages/storefront-events-sdk/package.json
Release v1.1.18 for storefront-sdk and storefront-collectors
=> chore: release v1.1.18

packages/storefront-events-collector/package.json, packages/storefront-events-sdk/package.json
Release v1.1.19
-   [x] My change requires a change to the documentation.
-   [x] I have updated the documentation accordingly.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
=> release v1.1.19

packages/storefront-events-collector/src/handlers/page/viewAEP.ts, packages/storefront-events-collector/src/index.ts
The cookie for segments will no longer be deleted on each page refresh
-   [] My change requires a change to the documentation.
-   [] I have added tests to cover my changes.
=> Changes for Segments Cookie

packages/storefront-events-collector/package.json, packages/storefront-events-collector/tests/contexts/product.test.ts, packages/storefront-events-collector/tests/handlers/product/addToCart.test.ts, packages/storefront-events-collector/tests/handlers/product/view.test.ts, packages/storefront-events-sdk/package.json
=> release v1.2.1

packages/storefront-events-collector/src/handlers/requisitionList/createRequisitionListAEP.ts, packages/storefront-events-collector/tests/handlers/requisitionList/createRequisitionListAEP.test.ts
added customer email inidentityMap for RequisitionListOpens event
Check that for RequisitionListOpens event identityMap contains email of logged in customer
=> DINT-840: Add customer email to identityMap for RequisitionListOpens event

packages/storefront-events-collector/src/handlers/requisitionList/removeFromRequisitionListAEP.ts, packages/storefront-events-collector/tests/handlers/requisitionList/removeFromRequisitionListAEP.test.ts
Adding email to removeFromRequisisionList event handler to be added to identity map.
https://jira.corp.adobe.com/browse/DINT-850
-   [x] All new and existing tests passed.
=> add email to removeFromReqList event

packages/storefront-events-collector/package.json, packages/storefront-events-sdk/package.json
Release v1.3.0 for `@adobe/magento-storefront-events-sdk` and `@adobe/magento-storefront-event-collector`
=> release v1.3.0

packages/storefront-events-collector/src/handlers/requisitionList/addToRequisitionListAEP.ts
=> DINT-889: convert Requisition List Id to string

packages/storefront-events-collector/package.json, packages/storefront-events-sdk/package.json
=> release v1.4.1

packages/storefront-events-collector/src/handlers/account/createAccountAEP.ts, packages/storefront-events-collector/src/handlers/account/editAccountAEP.ts, packages/storefront-events-collector/src/handlers/account/signInAEP.ts, packages/storefront-events-collector/src/handlers/account/signOutAEP.ts, packages/storefront-events-collector/src/handlers/checkout/placeOrderAEP.ts, packages/storefront-events-collector/src/handlers/product/addToCartAEP.ts, packages/storefront-events-collector/src/handlers/product/removeFromCartAEP.ts, packages/storefront-events-collector/src/handlers/product/viewAEP.ts, packages/storefront-events-collector/src/handlers/requisitionList/addToRequisitionListAEP.ts, packages/storefront-events-collector/src/handlers/requisitionList/createRequisitionListAEP.ts, packages/storefront-events-collector/src/handlers/requisitionList/removeFromRequisitionListAEP.ts, packages/storefront-events-collector/src/handlers/search/searchRequestSentAEP.ts, packages/storefront-events-collector/src/handlers/search/searchResponseReceivedAEP.ts, packages/storefront-events-collector/src/handlers/shoppingCart/initiateCheckoutAEP.ts, packages/storefront-events-collector/src/handlers/shoppingCart/openCartAEP.ts, packages/storefront-events-collector/src/handlers/shoppingCart/viewAEP.ts, packages/storefront-events-collector/src/types/aep/commerce.ts, packages/storefront-events-collector/src/utils/aep/commerceScope.ts, packages/storefront-events-collector/tests/handlers/checkout/placeOrderAEP.test.ts, packages/storefront-events-collector/tests/handlers/product/addToCartAEP.test.ts, packages/storefront-events-collector/tests/handlers/product/removeFromCartAEP.test.ts, packages/storefront-events-collector/tests/handlers/requisitionList/addToRequisitionListAEP.test.ts, packages/storefront-events-collector/tests/handlers/requisitionList/createRequisitionListAEP.test.ts, packages/storefront-events-collector/tests/handlers/requisitionList/removeFromRequisitionListAEP.test.ts, packages/storefront-events-collector/tests/handlers/shoppingCart/openCartAEP.test.ts
https://jira.corp.adobe.com/browse/DINT-974
=> DINT-974: include commerceScope in all AEP events

packages/storefront-events-collector/package.json, packages/storefront-events-sdk/package.json
bumping version for v1.5.0 release
=> prepare for release v1.5.0

packages/storefront-events-collector/package.json, packages/storefront-events-sdk/package.json, yarn.lock
=> prepare release v1.5.1

packages/storefront-events-collector/src/contexts/dataServicesExtension.ts, packages/storefront-events-collector/src/contexts/experiencePlatformConnectorExtension.ts, packages/storefront-events-collector/src/contexts/extension.ts, packages/storefront-events-collector/src/contexts/recommendationsExtension.ts, packages/storefront-events-collector/src/contexts/searchExtension.ts
- https://jira.corp.adobe.com/browse/DINT-1119
=> DINT-1119: better extension version tracking

packages/storefront-events-collector/package.json, packages/storefront-events-sdk/package.json, yarn.lock
=> prepare release v1.5.3

packages/storefront-events-collector/package.json, packages/storefront-events-sdk/package.json
=> Release version 1.5.4

packages/storefront-events-collector/README.md, packages/storefront-events-collector/src/events.ts, packages/storefront-events-collector/src/handlers/requisitionList/deleteRequisitionListAEP.ts, packages/storefront-events-collector/src/handlers/requisitionList/index.ts, packages/storefront-events-collector/src/types/aep/commerce.ts, packages/storefront-events-collector/tests/handlers/requisitionList/deleteRequisitionListAEP.test.ts, packages/storefront-events-sdk/src/PublishManager.ts, packages/storefront-events-sdk/src/SubscribeManager.ts, packages/storefront-events-sdk/src/UnsubscribeManager.ts, packages/storefront-events-sdk/src/events.ts, packages/storefront-events-sdk/src/types/events.ts, packages/storefront-events-sdk/tests/events.test.ts
=> DINT-1163: B2B Event Requisition List: DeleteRequisitionList

packages/storefront-events-collector/package.json, packages/storefront-events-sdk/package.json
=> Release version for 1.6.0

packages/storefront-events-collector/src/utils/aep/productListItems.ts
=> DINT-910: cart events have not rounded product price (decimal places)

packages/storefront-events-collector/src/utils/aep/productListItems.ts
Reverts adobe/commerce-events#130
=> Revert "DINT-910: cart events have not rounded product price (decimal places)"

packages/storefront-events-collector/package.json, packages/storefront-events-sdk/package.json
[](https://jira.corp.adobe.com/browse/DINT-1276)
=> Release version 1.7

packages/storefront-events-collector/package.json, packages/storefront-events-sdk/package.json
https://jira.corp.adobe.com/browse/MSRCH-4332
=> Release v1.7.1

packages/storefront-events-collector/package.json, packages/storefront-events-sdk/package.json
Preparing release for v1.8.0
- https://jira.corp.adobe.com/browse/DINT-407
- https://jira.corp.adobe.com/browse/DINT-433
- https://jira.corp.adobe.com/browse/DINT-421
- https://jira.corp.adobe.com/browse/DINT-910
- https://jira.corp.adobe.com/browse/DINT-911
-   [ ] I have …
=> prepare release for 1.8.0

packages/storefront-events-collector/src/utils/aep/order.ts
Support new codes
https://jira.corp.adobe.com/browse/DINT-1312
=> DINT-1312 Support payment codes for credit, debit, and gift card.

packages/storefront-events-collector/src/handlers/checkout/placeOrderAEP.ts, packages/storefront-events-collector/src/handlers/shoppingCart/initiateCheckoutAEP.ts, packages/storefront-events-collector/src/handlers/shoppingCart/viewAEP.ts
https://jira.corp.adobe.com/browse/DINT-1336
=> Dint 1336 fix discount amount on initiateCheckout and cart view AEP events.

packages/storefront-events-collector/package.json, packages/storefront-events-sdk/package.json
=> Release 1.8.1 bump release version

.github/PACKAGE_WORKFLOW.md, README.md, examples/events/product-page-view.md, packages/storefront-events-collector/README.md, packages/storefront-events-sdk/README.md
=> DINT-1332 - update cdn and product view docs

packages/storefront-events-collector/package.json, packages/storefront-events-sdk/package.json
=> update versions to 1.10.0

examples/events/snowplow-debugger/shopping-cart.json, packages/storefront-events-collector/src/schemas.ts
Adding minimum length to items.productSku, and minimum value of 1 to items.qty
https://jira.corp.adobe.com/browse/DINT-1562
Want to better restrict data coming into pipeline
Locally tested and Verified.  Want to merge to main and confirm with QA no bugs in code.
-   [ x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
-   [ ] I …
=> Dint 1562 - Update to Shopping Cart Schema3

packages/storefront-events-collector/package.json, packages/storefront-events-sdk/package.json
Updating version of release
Releasing recent schema updates and other changes
DINT-1562
=> Update versions of packages for release

examples/events/snowplow-debugger/data-services-extension.json, examples/events/snowplow-debugger/experience-platform-connector-extension.json, examples/events/snowplow-debugger/magento-extension.json, examples/events/snowplow-debugger/magento-js-tracker.json, examples/events/snowplow-debugger/recommendations-extension.json, examples/events/snowplow-debugger/search-extension.json, examples/events/snowplow-debugger/shopper.json
This PR adds additional schemas for local debugging.
=> Additional schemas for local debugging

examples/events/example-contexts/mock-storefront-context.md, examples/events/readme.md
=> Dint 1623 - Document impending new Storefront context required fields

examples/events/snowplow-debugger/storefront-instance.json, packages/storefront-events-collector/src/contexts/storefront.ts, packages/storefront-events-collector/src/schemas.ts, packages/storefront-events-collector/src/types/contexts.d.ts, packages/storefront-events-collector/src/utils/ccdm.ts, packages/storefront-events-collector/tests/contexts/storefront.test.ts, packages/storefront-events-collector/tests/utils/mocks/context.ts, packages/storefront-events-sdk/src/types/schemas/storefrontInstance.ts
=> MSRCH-4785: Update the storefront collector with CCDM concepts

packages/storefront-events-collector/package.json, packages/storefront-events-sdk/package.json
=> Release 1.13.0

examples/events/recs-item-add-to-cart.md, examples/events/recs-item-click.md
=> Fix rec-item-click and rec-item-add-to-cart event documentation

.github/workflows/storefront-merge-to-main.yml
=> fix workflow for QA DEPLOYMENT
